project_id = "pygsmujlhvyubrqnbwwq"

[functions.process-report]
verify_jwt = false

[functions.feed]
verify_jwt = false

[functions.generate-company-profile]
verify_jwt = false

[functions.send-push]
verify_jwt = false
